In [1]:
import numpy as np
import tensorflow as tf
from sklearn import datasets
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam


Using TensorFlow backend.


In [2]:
data = datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [3]:
X = data.data
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [4]:
y = data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
X_train

array([[1.519e+01, 1.321e+01, 9.765e+01, ..., 8.178e-02, 2.487e-01,
        6.766e-02],
       [1.434e+01, 1.347e+01, 9.251e+01, ..., 1.087e-01, 3.062e-01,
        6.072e-02],
       [1.120e+01, 2.937e+01, 7.067e+01, ..., 0.000e+00, 1.566e-01,
        5.905e-02],
       ...,
       [1.154e+01, 1.444e+01, 7.465e+01, ..., 6.918e-02, 2.329e-01,
        8.134e-02],
       [1.147e+01, 1.603e+01, 7.302e+01, ..., 6.548e-02, 2.851e-01,
        8.763e-02],
       [1.497e+01, 1.976e+01, 9.550e+01, ..., 5.754e-02, 2.646e-01,
        6.085e-02]])

In [8]:
X_test

array([[1.131e+01, 1.904e+01, 7.180e+01, ..., 6.961e-02, 2.400e-01,
        6.641e-02],
       [2.026e+01, 2.303e+01, 1.324e+02, ..., 1.573e-01, 3.689e-01,
        8.368e-02],
       [9.423e+00, 2.788e+01, 5.926e+01, ..., 0.000e+00, 2.475e-01,
        6.969e-02],
       ...,
       [1.051e+01, 2.309e+01, 6.685e+01, ..., 3.125e-02, 2.227e-01,
        6.777e-02],
       [1.096e+01, 1.762e+01, 7.079e+01, ..., 9.861e-02, 2.289e-01,
        8.278e-02],
       [1.486e+01, 2.321e+01, 1.004e+02, ..., 1.727e-01, 3.000e-01,
        8.701e-02]])

In [9]:
y_train

array([1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,

In [10]:
y_test

array([1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0])

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [12]:
X_train=scaler.transform(X_train)
X_train

array([[ 0.26271429, -1.39895153,  0.19414547, ..., -0.53529154,
        -0.68029004, -0.90963319],
       [ 0.02624104, -1.33955584, -0.01288649, ..., -0.13002605,
         0.22732188, -1.2901614 ],
       [-0.84731895,  2.29271844, -0.89257095, ..., -1.76644356,
        -2.13404757, -1.38172943],
       ...,
       [-0.75272966, -1.11796427, -0.73226215, ..., -0.72497747,
        -0.92968601, -0.15954299],
       [-0.77220392, -0.75473684, -0.79791626, ..., -0.7806789 ,
        -0.10573224,  0.18534497],
       [ 0.20150945,  0.09736272,  0.1075465 , ..., -0.90021114,
        -0.42931562, -1.28303335]])

In [13]:
model = Sequential()
model.add(Dense(1, input_dim=30, activation="sigmoid"))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 31        
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.compile(loss="binary_crossentropy", optimizer=Adam(lr=0.001), metrics=['acc'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [18]:
model.fit(X_train, y_train, epochs=1000)


Epoch 1/1000
455/455 [==============================] - 0s 269us/step - loss: 0.4264 - acc: 0.8527
Epoch 2/1000
455/455 [==============================] - 0s 40us/step - loss: 0.3865 - acc: 0.8725
Epoch 3/1000
455/455 [==============================] - 0s 34us/step - loss: 0.3537 - acc: 0.8835
Epoch 4/1000
455/455 [==============================] - 0s 33us/step - loss: 0.3259 - acc: 0.8989
Epoch 5/1000
455/455 [==============================] - 0s 34us/step - loss: 0.3036 - acc: 0.9099
Epoch 6/1000
455/455 [==============================] - 0s 35us/step - loss: 0.2843 - acc: 0.9121
Epoch 7/1000
455/455 [==============================] - 0s 33us/step - loss: 0.2675 - acc: 0.9143
Epoch 8/1000
455/455 [==============================] - 0s 33us/step - loss: 0.2530 - acc: 0.9187
Epoch 9/1000
455/455 [==============================] - 0s 33us/step - loss: 0.2402 - acc: 0.9275
Epoch 10/1000
455/455 [==============================] - 0s 32us/step - loss: 0.2290 - acc: 0.9319
Epoch 11/1000
455

455/455 [==============================] - 0s 31us/step - loss: 0.0849 - acc: 0.9802
Epoch 82/1000
455/455 [==============================] - 0s 32us/step - loss: 0.0845 - acc: 0.9802
Epoch 83/1000
455/455 [==============================] - 0s 31us/step - loss: 0.0841 - acc: 0.9802
Epoch 84/1000
455/455 [==============================] - 0s 33us/step - loss: 0.0836 - acc: 0.9802
Epoch 85/1000
455/455 [==============================] - 0s 31us/step - loss: 0.0832 - acc: 0.9802
Epoch 86/1000
455/455 [==============================] - 0s 31us/step - loss: 0.0828 - acc: 0.9802
Epoch 87/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0824 - acc: 0.9824
Epoch 88/1000
455/455 [==============================] - 0s 31us/step - loss: 0.0820 - acc: 0.9824
Epoch 89/1000
455/455 [==============================] - 0s 26us/step - loss: 0.0815 - acc: 0.9824
Epoch 90/1000
455/455 [==============================] - 0s 33us/step - loss: 0.0811 - acc: 0.9824
Epoch 91/1000
455/455 [=

455/455 [==============================] - 0s 33us/step - loss: 0.0649 - acc: 0.9868
Epoch 164/1000
455/455 [==============================] - 0s 28us/step - loss: 0.0648 - acc: 0.9868
Epoch 165/1000
455/455 [==============================] - 0s 31us/step - loss: 0.0647 - acc: 0.9868
Epoch 166/1000
455/455 [==============================] - 0s 29us/step - loss: 0.0646 - acc: 0.9868
Epoch 167/1000
455/455 [==============================] - 0s 33us/step - loss: 0.0644 - acc: 0.9868
Epoch 168/1000
455/455 [==============================] - 0s 29us/step - loss: 0.0643 - acc: 0.9868
Epoch 169/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0641 - acc: 0.9868
Epoch 170/1000
455/455 [==============================] - 0s 29us/step - loss: 0.0640 - acc: 0.9868
Epoch 171/1000
455/455 [==============================] - 0s 28us/step - loss: 0.0639 - acc: 0.9868
Epoch 172/1000
455/455 [==============================] - 0s 32us/step - loss: 0.0637 - acc: 0.9868
Epoch 173/1000


455/455 [==============================] - 0s 31us/step - loss: 0.0571 - acc: 0.9868
Epoch 246/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0571 - acc: 0.9868
Epoch 247/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0570 - acc: 0.9868
Epoch 248/1000
455/455 [==============================] - 0s 25us/step - loss: 0.0570 - acc: 0.9868
Epoch 249/1000
455/455 [==============================] - 0s 32us/step - loss: 0.0568 - acc: 0.9868
Epoch 250/1000
455/455 [==============================] - 0s 26us/step - loss: 0.0568 - acc: 0.9868
Epoch 251/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0568 - acc: 0.9868
Epoch 252/1000
455/455 [==============================] - 0s 28us/step - loss: 0.0567 - acc: 0.9868
Epoch 253/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0567 - acc: 0.9868
Epoch 254/1000
455/455 [==============================] - 0s 29us/step - loss: 0.0566 - acc: 0.9868
Epoch 255/1000


455/455 [==============================] - 0s 33us/step - loss: 0.0531 - acc: 0.9890
Epoch 328/1000
455/455 [==============================] - 0s 26us/step - loss: 0.0530 - acc: 0.9890
Epoch 329/1000
455/455 [==============================] - 0s 34us/step - loss: 0.0530 - acc: 0.9890
Epoch 330/1000
455/455 [==============================] - 0s 26us/step - loss: 0.0529 - acc: 0.9890
Epoch 331/1000
455/455 [==============================] - 0s 31us/step - loss: 0.0529 - acc: 0.9890
Epoch 332/1000
455/455 [==============================] - 0s 26us/step - loss: 0.0528 - acc: 0.9890
Epoch 333/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0528 - acc: 0.9868
Epoch 334/1000
455/455 [==============================] - 0s 29us/step - loss: 0.0528 - acc: 0.9868
Epoch 335/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0528 - acc: 0.9868
Epoch 336/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0527 - acc: 0.9868
Epoch 337/1000


455/455 [==============================] - 0s 30us/step - loss: 0.0506 - acc: 0.9890
Epoch 410/1000
455/455 [==============================] - 0s 28us/step - loss: 0.0506 - acc: 0.9890
Epoch 411/1000
455/455 [==============================] - 0s 31us/step - loss: 0.0506 - acc: 0.9890
Epoch 412/1000
455/455 [==============================] - 0s 28us/step - loss: 0.0505 - acc: 0.9890
Epoch 413/1000
455/455 [==============================] - 0s 32us/step - loss: 0.0505 - acc: 0.9890
Epoch 414/1000
455/455 [==============================] - 0s 28us/step - loss: 0.0505 - acc: 0.9868
Epoch 415/1000
455/455 [==============================] - 0s 33us/step - loss: 0.0504 - acc: 0.9868
Epoch 416/1000
455/455 [==============================] - 0s 27us/step - loss: 0.0504 - acc: 0.9868
Epoch 417/1000
455/455 [==============================] - 0s 32us/step - loss: 0.0504 - acc: 0.9890
Epoch 418/1000
455/455 [==============================] - 0s 29us/step - loss: 0.0504 - acc: 0.9890
Epoch 419/1000


455/455 [==============================] - 0s 28us/step - loss: 0.0489 - acc: 0.9912
Epoch 492/1000
455/455 [==============================] - 0s 33us/step - loss: 0.0489 - acc: 0.9912
Epoch 493/1000
455/455 [==============================] - 0s 26us/step - loss: 0.0489 - acc: 0.9912
Epoch 494/1000
455/455 [==============================] - 0s 32us/step - loss: 0.0490 - acc: 0.9912
Epoch 495/1000
455/455 [==============================] - 0s 27us/step - loss: 0.0488 - acc: 0.9912
Epoch 496/1000
455/455 [==============================] - 0s 34us/step - loss: 0.0488 - acc: 0.9912
Epoch 497/1000
455/455 [==============================] - 0s 27us/step - loss: 0.0489 - acc: 0.9912
Epoch 498/1000
455/455 [==============================] - 0s 35us/step - loss: 0.0488 - acc: 0.9912
Epoch 499/1000
455/455 [==============================] - 0s 28us/step - loss: 0.0488 - acc: 0.9912
Epoch 500/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0488 - acc: 0.9912
Epoch 501/1000


455/455 [==============================] - 0s 33us/step - loss: 0.0476 - acc: 0.9912
Epoch 574/1000
455/455 [==============================] - 0s 26us/step - loss: 0.0477 - acc: 0.9912
Epoch 575/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0476 - acc: 0.9912
Epoch 576/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0476 - acc: 0.9912
Epoch 577/1000
455/455 [==============================] - 0s 32us/step - loss: 0.0475 - acc: 0.9912
Epoch 578/1000
455/455 [==============================] - 0s 28us/step - loss: 0.0475 - acc: 0.9912
Epoch 579/1000
455/455 [==============================] - 0s 29us/step - loss: 0.0476 - acc: 0.9912
Epoch 580/1000
455/455 [==============================] - 0s 32us/step - loss: 0.0475 - acc: 0.9912
Epoch 581/1000
455/455 [==============================] - 0s 28us/step - loss: 0.0474 - acc: 0.9912
Epoch 582/1000
455/455 [==============================] - 0s 33us/step - loss: 0.0475 - acc: 0.9912
Epoch 583/1000


455/455 [==============================] - 0s 28us/step - loss: 0.0466 - acc: 0.9912
Epoch 656/1000
455/455 [==============================] - 0s 29us/step - loss: 0.0466 - acc: 0.9912
Epoch 657/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0466 - acc: 0.9890
Epoch 658/1000
455/455 [==============================] - 0s 29us/step - loss: 0.0466 - acc: 0.9890
Epoch 659/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0465 - acc: 0.9890
Epoch 660/1000
455/455 [==============================] - 0s 26us/step - loss: 0.0465 - acc: 0.9912
Epoch 661/1000
455/455 [==============================] - 0s 33us/step - loss: 0.0465 - acc: 0.9912
Epoch 662/1000
455/455 [==============================] - 0s 26us/step - loss: 0.0466 - acc: 0.9912
Epoch 663/1000
455/455 [==============================] - 0s 31us/step - loss: 0.0466 - acc: 0.9890
Epoch 664/1000
455/455 [==============================] - 0s 26us/step - loss: 0.0465 - acc: 0.9890
Epoch 665/1000


455/455 [==============================] - 0s 29us/step - loss: 0.0457 - acc: 0.9912
Epoch 738/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0456 - acc: 0.9912
Epoch 739/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0457 - acc: 0.9912
Epoch 740/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0456 - acc: 0.9912
Epoch 741/1000
455/455 [==============================] - 0s 29us/step - loss: 0.0457 - acc: 0.9912
Epoch 742/1000
455/455 [==============================] - 0s 28us/step - loss: 0.0457 - acc: 0.9912
Epoch 743/1000
455/455 [==============================] - 0s 34us/step - loss: 0.0457 - acc: 0.9912
Epoch 744/1000
455/455 [==============================] - 0s 27us/step - loss: 0.0456 - acc: 0.9912
Epoch 745/1000
455/455 [==============================] - 0s 33us/step - loss: 0.0457 - acc: 0.9912
Epoch 746/1000
455/455 [==============================] - 0s 27us/step - loss: 0.0456 - acc: 0.9912
Epoch 747/1000


455/455 [==============================] - 0s 28us/step - loss: 0.0450 - acc: 0.9912
Epoch 820/1000
455/455 [==============================] - 0s 32us/step - loss: 0.0449 - acc: 0.9912
Epoch 821/1000
455/455 [==============================] - 0s 28us/step - loss: 0.0450 - acc: 0.9912
Epoch 822/1000
455/455 [==============================] - 0s 29us/step - loss: 0.0450 - acc: 0.9912
Epoch 823/1000
455/455 [==============================] - 0s 27us/step - loss: 0.0449 - acc: 0.9912
Epoch 824/1000
455/455 [==============================] - 0s 32us/step - loss: 0.0449 - acc: 0.9912
Epoch 825/1000
455/455 [==============================] - 0s 25us/step - loss: 0.0449 - acc: 0.9912
Epoch 826/1000
455/455 [==============================] - 0s 33us/step - loss: 0.0449 - acc: 0.9912
Epoch 827/1000
455/455 [==============================] - 0s 28us/step - loss: 0.0449 - acc: 0.9912
Epoch 828/1000
455/455 [==============================] - 0s 32us/step - loss: 0.0450 - acc: 0.9912
Epoch 829/1000


455/455 [==============================] - 0s 30us/step - loss: 0.0443 - acc: 0.9912
Epoch 902/1000
455/455 [==============================] - 0s 29us/step - loss: 0.0443 - acc: 0.9912
Epoch 903/1000
455/455 [==============================] - 0s 34us/step - loss: 0.0443 - acc: 0.9912
Epoch 904/1000
455/455 [==============================] - 0s 29us/step - loss: 0.0443 - acc: 0.9912
Epoch 905/1000
455/455 [==============================] - 0s 31us/step - loss: 0.0443 - acc: 0.9912
Epoch 906/1000
455/455 [==============================] - 0s 26us/step - loss: 0.0442 - acc: 0.9912
Epoch 907/1000
455/455 [==============================] - 0s 32us/step - loss: 0.0442 - acc: 0.9912
Epoch 908/1000
455/455 [==============================] - 0s 28us/step - loss: 0.0443 - acc: 0.9912
Epoch 909/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0442 - acc: 0.9912
Epoch 910/1000
455/455 [==============================] - 0s 26us/step - loss: 0.0443 - acc: 0.9890
Epoch 911/1000


455/455 [==============================] - 0s 32us/step - loss: 0.0437 - acc: 0.9912
Epoch 984/1000
455/455 [==============================] - 0s 27us/step - loss: 0.0437 - acc: 0.9912
Epoch 985/1000
455/455 [==============================] - 0s 28us/step - loss: 0.0437 - acc: 0.9912
Epoch 986/1000
455/455 [==============================] - 0s 30us/step - loss: 0.0436 - acc: 0.9912
Epoch 987/1000
455/455 [==============================] - 0s 26us/step - loss: 0.0438 - acc: 0.9912
Epoch 988/1000
455/455 [==============================] - 0s 31us/step - loss: 0.0437 - acc: 0.9912
Epoch 989/1000
455/455 [==============================] - 0s 27us/step - loss: 0.0437 - acc: 0.9912
Epoch 990/1000
455/455 [==============================] - 0s 32us/step - loss: 0.0437 - acc: 0.9912
Epoch 991/1000
455/455 [==============================] - 0s 26us/step - loss: 0.0436 - acc: 0.9912
Epoch 992/1000
455/455 [==============================] - 0s 32us/step - loss: 0.0436 - acc: 0.9912
Epoch 993/1000


In [20]:
X_test = scaler.transform(X_test)
X_test

array([[ -4.1904154 ,  -4.43204165,  -3.77317729, ..., -12.5831191 ,
        -17.51160854, -58.25381667],
       [ -3.49770898,  -4.22381518,  -3.67486197, ...,   7.29060317,
         14.60410752,  -6.33232978],
       [ -4.33646423,  -3.97070783,  -3.79352175, ..., -28.35926013,
        -15.64296718, -48.39264255],
       ...,
       [ -4.25233329,  -4.22068396,  -3.781208  , ..., -21.27688106,
        -21.82194126, -54.16503716],
       [ -4.21750448,  -4.5061473 ,  -3.77481588, ...,  -6.01067132,
        -20.27719774,  -9.03813975],
       [ -3.91565475,  -4.21442151,  -3.72677765, ...,  10.78079958,
         -2.56247771,   3.67916712]])

In [21]:
pred = model.predict(X_test)
pred

array([[0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [9.9972141e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [9.2387199e-07],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [2.9802322e-08],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.000000

In [22]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 30)
print("predict01")
print(predict01)

predict01
[[0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]]


In [23]:
predict02 = predict01.flatten()
predict02

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1])

In [24]:
predict03 = (predict02 == y_test)
predict03

array([False, False,  True,  True,  True,  True, False, False,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False, False, False,  True,  True, False, False,  True,  True,
        True, False, False, False, False, False, False,  True, False,
       False,  True, False, False,  True,  True,  True,  True, False,
        True, False, False,  True, False,  True, False,  True,  True,
        True, False, False,  True, False,  True, False, False,  True,
        True,  True,  True, False,  True,  True, False, False,  True,
        True, False,  True, False,  True,  True, False, False,  True,
        True,  True, False, False, False,  True, False,  True,  True,
        True, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True,  True, False,  True, False,  True,
        True, False,  True, False, False, False])

In [25]:
np.sum(predict03)

59

In [26]:
len(predict03)

114

In [27]:
acc=np.sum(predict03)/len(predict03)
acc

0.5175438596491229