In [2]:
import numpy as np
import tensorflow as tf

In [5]:
#tf.enable_eager_execution()

AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'

In [8]:
X = np.array([[0., 0.], [0., 1.], [1., 0.], [1., 1.]], dtype="float32")
y = np.array([[0.], [0.], [0.], [1.]], dtype="float32")

In [7]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [9]:
y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [11]:
w = np.array([[1], [2]], dtype="float32")
b = np.array([3], dtype="float32")

In [12]:
w

array([[1.],
       [2.]], dtype=float32)

In [13]:
b

array([3.], dtype=float32)

In [14]:
np.dot(X, w)

array([[0.],
       [2.],
       [1.],
       [3.]], dtype=float32)

In [15]:
np.dot(X, w) + b

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [16]:
def sigmoid(h):
    return 1 / (1 + np.exp(-h))

In [17]:
hypothesis = np.dot(X, w) + b
hypothesis

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [18]:
hypothesis = sigmoid(np.dot(X, w) + b)
hypothesis

array([[0.95257413],
       [0.9933072 ],
       [0.98201376],
       [0.9975274 ]], dtype=float32)

In [19]:
(hypothesis - y)

array([[ 0.95257413],
       [ 0.9933072 ],
       [ 0.98201376],
       [-0.00247258]], dtype=float32)

In [20]:
X.T

array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]], dtype=float32)

In [21]:
X.T[0]

array([0., 0., 1., 1.], dtype=float32)

In [23]:
X_col_2d1 = X.T[0].reshape(1, -1)
X_col_2d1

array([[0., 0., 1., 1.]], dtype=float32)

In [25]:
w1_gred = 1/4 * np.sum(np.dot(X_col_2d1, (hypothesis - y)))
print("w_gred:", w1_gred)

w_gred: 0.24488529562950134


In [26]:
X.T[1]

array([0., 1., 0., 1.], dtype=float32)

In [27]:
X_col_2d2 = X.T[1].reshape(1, -1)
X_col_2d2

array([[0., 1., 0., 1.]], dtype=float32)

In [28]:
w2_gred = 1/4 * np.sum(np.dot((hypothesis - y), X_col_2d2))
print("w_gred:", w2_gred)

w_gred: 1.4627113342285156


In [29]:
b_gred = 1/4 * np.sum(hypothesis - y)
print("b_gred:", b_gred)

b_gred: 0.731355607509613
